# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d795de9c17bbba57cca85a070312b46d73103fb6b427d5cf457a4997c15c14626991538c0b0fcd89ce4de956259f7b1d10a1af9f86933715bde40dadac325fdb

test:
  secret_key_base: b1eb752dbe8556ee42739353b84a2ad2addbf3c3748724ff769d545de149474c9912d0c6f3d4d0b2c2b6ab8fdb869dcdd2fc27d5dd554106988c1aa77f7b6e19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
